Function.prototype.delay=function(a,b,c){var d=this;return setTimeout(function(){d.apply(b,c)},a)};Function.prototype.periodical=function(a,b,c){var d=this;return setInterval(function(){d.apply(b,c)},a)};
window.onerror=function(a,b,c){Crossrider.Utils.internalDebug("JAVASCRIPT ERROR");Crossrider.Utils.internalDebug("ERROR MESSAGE:"+a);Crossrider.Utils.internalDebug("ON FILE: "+b+" IN LINE NUMBER "+c);if(0<=b.indexOf("background.html"))return!1;try{var d="";if(0<a.indexOf(":"))var e=a.replace("Uncaught ","").trim().split(":"),d=e[0].trim(),a=e[1].trim();var g=chrome.extension.getURL("manifest.json").replace("manifest.json",""),b=b.replace(g,""),j="msg="+escape(a)+"&errtype="+escape(d),j=j+("&fileName="+
escape(b)+"&lineNumber="+escape(c));Crossrider._reportError(j)}catch(h){Crossrider.Utils.internalDebug("window.onerror Error : "+h.message)}return!1};
var Crossrider={manifest:{},_tabs:{},debug:!1,_userCode:"",_bgCode:"",_faye:{client:null,callbacks:{background:{}},asyncCallbacks:{}},_contextMenus:{},_cookies:{mysite:{}},_notifications:{},_cookieInUpdate:{},_firstLoad:!1,isStaging:!1,isDuringUpdate:!1,UPDATE_INTERVAL:360,init:function(){this._loadLocalManifest();this._initInternalMessaging();this._initStorage();chrome.tabs.onRemoved.addListener(function(a){this._unsubscribeAllInTab(a)}.bind(this));chrome.tabs.onSelectionChanged.addListener(this._onTabSelectionChanged.bind(this))},
_setInstallationTime:function(a,b){try{var c=this._cookies.InstallationTime;"undefined"===typeof c&&(c=a||Math.round((new Date).getTime()/1E3),this.setCookie("InstallationTime",c,new Date(2030,1,1,0,0,0,0),void 0,b))}catch(d){Crossrider.Utils.internalDebug("_setInstallationTime Error : "+d.message)}},_initStorage:function(){CookieStore.init(this.appID);DataStore.init(this.appID);CookieStore.getCookies(this._onCookiesRead.bind(this))},_onCookiesRead:function(a){this._cookies=a||{};this._cookies.mysite=
{};this._startApplication()},_startApplication:function(){this.debug?(this._loadRemoteManifest(),this._getSiteCookies()):DataStore.getData(this.appID,this._onAppDataLoad.bind(this))},_getSiteCookies:function(){void 0!==this.manifest.domain&&null!==this.manifest.domain?chrome.cookies.getAll({url:"http://"+this.manifest.domain,domain:this.manifest.domain},function(a){for(var b=0,c=a.length;b<c;b++){var d=a[b],e=void 0!==d.expirationDate?(new Date(1E3*d.expirationDate)).getTime():null;this._cookies.mysite[d.name]=
{value:d.value,expires:e}}this.setToolbarUniqueID()}.bind(this)):this.setToolbarUniqueID()},_initAppAPI:function(){window.appAPI=new AppApi;window.appAPI.init(this._cookies);chrome.cookies.onChanged.addListener(this._onCookieChange.bind(this));this._fb_bridge=FBBridge.init(this.manifest.remotefbapiurl,this.appID,!1);this._loadUserScript();this._loadBackgroundScript();this._firstLoad="false"!==localStorage.firstLoad;var a=this;if(this._firstLoad&&(this._setInstallationTime(void 0,function(){a.debug||
(a._reportInstall(),a._reportUpdate(),a._sendDailyStats())}),!this.debug))this._showThankyouPage(),localStorage.firstLoad="false";this.debug||this._checkNextUpdate.periodical(6E4,this);var b=document.createEvent("Events");b.initEvent("cr_ready",!0,!1);document.dispatchEvent(b)},_onAppDataLoad:function(a){var b=localStorage.crx_version;a.manifest&&a.app&&b===this.manifest.version?(this._parseManifestXML(a.manifest.value),this._user_script=a.app||{value:"",version:this.manifest.ver},this._bg_script=
a.bg_script||{value:"",version:this.manifest.backgroundver},this._getSiteCookies()):this._updateAppAndManifest(!0)||setTimeout(function(){Crossrider._onAppDataLoad(a)},6E4)},_loadLocalManifest:function(){var a=chrome.extension.getURL("manifest.json"),b=a.replace(/chrome\-extension\:\/\//,"");this.extensionID=b.substr(0,b.indexOf("/"));this.manifest=JSON.parse(Crossrider.Utils.fetchScript(a));this.manifest.platform="CH";this.debug=this.manifest.crossrider.hasOwnProperty("debug")?this.manifest.crossrider.debug:
!1;this.appID=this.manifest.crossrider.appID;if(this.manifest.crossrider.hasOwnProperty("is_staging"))this.isStaging=this.manifest.crossrider.is_staging},_loadRemoteManifest:function(){var a="https://crossrider.cotssl.net/plugin/apps/manifest/"+this.appID+".xml";this.isStaging&&(a="http://static-staging.crossrider.com/plugin/apps/manifest/"+this.appID+".xml");if(this.manifest&&this.manifest.manifest)a=this.manifest.manifest;(a=Crossrider.Utils.fetchScript(a))&&this._parseManifestXML(a);return a},
_updateAppAndManifest:function(a){var b=this._loadRemoteManifest();if(!b)return!1;var c=Crossrider.Utils.toInt(this.manifest.ver),d=Crossrider.Utils.toInt(this.manifest.backgroundver),e=this._user_script?Crossrider.Utils.toInt(this._user_script.version):0,g=this._bg_script?Crossrider.Utils.toInt(this._bg_script.version):0,j=c>e,h=d>g,f=this;DataStore.saveManifest(this.appID,b,function(){function b(a,c){var d=Crossrider.Utils.fetchScript(a);d?c(d):setTimeout(function(){b(a,c)},6E4)}function c(a,b){DataStore.saveBGApp(f.appID,
a,f.manifest.backgroundver,function(){f._bg_script={value:a,version:f.manifest.backgroundver};b?b(d):d()})}function d(){void 0!==f._bg_script&&self.location.reload()}function g(a){f.manifest.backgroundjs?b(f.manifest.backgroundjs,function(b){c(b,a)}):c("",a)}function l(b,c){f._user_script={value:b,version:f.manifest.ver};f._loadUserScript();a||f._reportUpdate(e);DataStore.saveApp(f.appID,b,f.manifest.ver,function(){c&&c()})}if(void 0===localStorage.crx_version||localStorage.crx_version!==f.manifest.version)localStorage.crx_version=
f.manifest.version;j?b(f.manifest.jslink,function(b){h?g(function(a){l(b,function(){a&&a()})}):l(b,function(){a&&f._getSiteCookies()})}):h&&g(function(a){a&&a()})});return!0},_parseManifestXML:function(a){xDoc=(new DOMParser).parseFromString(a,"text/xml");for(var a=xDoc.getElementsByTagName("CrAppInfo")[0].childNodes,b=0,c=a.length;b<c;b++){var d=a[b];d&&1===d.nodeType&&(this.manifest[d.nodeName.toLowerCase()]=0<d.childNodes.length?"NA"===d.childNodes[0].nodeValue?null:d.childNodes[0].nodeValue:null)}this.manifest.updateinterval=
this.manifest.hasOwnProperty("updateinterval")?parseInt(this.manifest.updateinterval):this.UPDATE_INTERVAL},_initInternalMessaging:function(){chrome.extension.onRequest.addListener(this._onRequest.bind(this))},_onRequest:function(a,b,c){var d=a.action;if(d&&"function"===typeof this[d]){var e=a.params&&"function"===typeof a.params.push?a.params:[];!0===a.passCallback&&e.push(c);"addUserScripts"===d&&e.push(b.tab);this[d].apply(this,e)}!a.passCallback&&c&&"function"===typeof c&&c()},_loadBackgroundScript:function(){if(this.debug){var a=
this.manifest.crossrider.background_script;/^https?\:\/\//.test(a)||(a=chrome.extension.getURL(a));this._bg_script={value:Crossrider.Utils.fetchScript(a),version:this.manifest.backgroundver}}if(void 0!==this._bg_script)this._bgCode=Crossrider.CodeParser.parse(this._bg_script.value),Crossrider.Workers.execLocal("function _cr_crossrider_ready_to_run_the_user_background_code() { "+this._bgCode+" };","background_script")},_loadUserScript:function(){if(this.debug){Crossrider.Workers.reset();var a=this.manifest.crossrider.user_script;
/^https?\:\/\//.test(a)||(a=chrome.extension.getURL(a));this._parseUserScripts(Crossrider.Utils.fetchScript(a))}else this._parseUserScripts(this._user_script.value)},_parseUserScripts:function(a){this._userCode=Crossrider.CodeParser.reset().parse(a);Crossrider.Workers.types.forEach(function(a){var a=Crossrider.Workers[a],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];d.code=Crossrider.CodeParser.parse(d.code)}});Crossrider.Workers.start()},addUserScripts:function(a){this.debug&&this._loadUserScript();
var b=Crossrider.CodeParser.includes.DOM.css;a.selected?chrome.windows.getLastFocused(function(){if(void 0===this._cookies.mysite)this._cookies.mysite={};chrome.tabs.get(a.id,function(a){a&&!a.url.match(/^(https?\:\/\/(www|ssl)\.facebook\.com\/login\.php|https?\:\/\/www\.facebook\.com\/connect\/uiserver\.php|https?\:\/\/static\.ak\.fbcdn\.net\/connect\/xd_proxy\.php|https?\:\/\/.*?fbcdn.net\/connect\/xd_proxy\.php).*/)&&0==a.url.indexOf("http")&&chrome.tabs.sendRequest(a.id,{action:"initContentScript",
passCallback:!0,params:[b,JSON.stringify(this._cookies),a.id,this._bic,this.manifest]},function(){"string"==typeof this._userCode&&0<this._userCode.length&&chrome.tabs.executeScript(a.id,{code:this._userCode})}.bind(this))}.bind(this))}.bind(this)):this._tabs[a.id]=!0},_onTabSelectionChanged:function(a){this._tabs.hasOwnProperty(a)&&(delete this._tabs[a],this.addUserScripts({id:a,selected:!0}))},request:function(a,b){return(new XHR({url:a.url,method:a.method,data:a.data,callback:b,async:void 0===
a.async?!0:a.async})).send()},openURL:function(a,b){"current"===b?chrome.tabs.getSelected(null,function(b){b&&chrome.tabs.update(b.id,{url:a})}):chrome["tab"===b?"tabs":"windows"].create({url:a})},superAlert:function(a){alert(a)},connect:function(a){if(null===this._faye.client)this._faye.client=new Faye.Client("http://push.crossrider.com:8000/faye",{timeout:120});"function"===typeof a&&a()},publish:function(a,b){"string"!==typeof b&&(b=b.hasOwnProperty&&!b.length?JSON.stringify(b):b.toString());this._faye.client.publish(this._getChannelURL(a),
b)},subscribe:function(a,b,c,d){if("function"===typeof b)return this._faye.callbacks.background[a]||(this._faye.callbacks.background[a]=this._faye.client.subscribe(this._getChannelURL(a),b)),this._faye.callbacks.background[a];b=d?"asyncCallbacks":"callbacks";this._faye[b][c]||(this._faye[b][c]={});this._faye[b][c][a]||(this._faye[b][c][a]=this._faye.client.subscribe(this._getChannelURL(a),function(b){chrome.tabs.sendRequest(c,{action:"respond",params:[a,b,d]},function(){})}));return this._faye[b][c][a]},
unsubscribe:function(a,b,c){c=c?"asyncCallbacks":"callbacks";this._faye[c][b][a]&&(this._faye[c][b][a].cancel(),delete this._faye[c][b][a])},_unsubscribeAllInTab:function(a){if(this._faye.callbacks[a]){for(var b in this._faye.callbacks[a])this._faye.callbacks[a].hasOwnProperty(b)&&this.unsubscribe(b,a);delete this._faye.callbacks[a]}if(this._faye.asyncCallbacks[a]){for(b in this._faye.asyncCallbacks[a])this._faye.asyncCallbacks[a].hasOwnProperty(b)&&this.unsubscribe(b,a,!0);delete this._faye.asyncCallbacks[a]}},
_getChannelURL:function(a){return["/",(this.debug?"Debug":"")+"app",this.appID,"ZZZ-",a].join("")},setCookie:function(a,b,c,d,e){if("mysite"!==a){var g=(new Date).getTime(),c=(new Date(c)).getTime();g>c?this._cookies[a]&&this.unsetCookie(a):CookieStore.setCookie(a,b,c,function(){this._cookies[a]={value:b,expires:c};this._broadcastAllTabs("updateCookie",[a,this._cookies[a]],d);e&&e()}.bind(this),function(){this._broadcastAllTabs("unsetCookie",[a])}.bind(this))}},unsetCookie:function(a){this._cookies[a]&&
CookieStore.unsetCookie(a,function(){delete this._cookies[a];this._broadcastAllTabs("unsetCookie",[a])}.bind(this))},setRealCookie:function(a,b,c){if(void 0!==this.manifest.domain&&null!==this.manifest.domain){var d=(new Date).getTime(),c=c?(new Date(c)).getTime():null;null!==c&&d>c?this._cookies.mysite[a]&&this.unsetRealCookie(a):(null!==c?chrome.cookies.set({url:"http://"+this.manifest.domain,name:a,value:b,expirationDate:Math.round(c/1E3),path:"/"}):chrome.cookies.set({url:"http://"+this.manifest.domain,
name:a,value:b,path:"/"}),this._cookies.mysite[a]={value:b,expires:c})}},unsetRealCookie:function(a){void 0!==this.manifest.domain&&null!==this.manifest.domain&&this._cookies.mysite[a]&&(chrome.cookies.remove({url:"http://"+this.manifest.domain,name:a}),delete this._cookies.mysite[a])},_onCookieChange:function(a){if(!(void 0===this.manifest.domain||null===this.manifest.domain||0>a.cookie.domain.indexOf(this.manifest.domain)))if(a.removed)void 0!==this._cookies.mysite[a.cookie.name]&&delete this._cookies.mysite[a.cookie.name];
else{var b=a.cookie.expirationDate?1E3*a.cookie.expirationDate:null,c=(new Date).getTime();if(null!==b&&c>b||a.cookie.session)b=null;this._cookies.mysite[a.cookie.name]={value:a.cookie.value,expires:b}}},_broadcastAllTabs:function(a,b,c,d){chrome.windows.getAll({populate:!0},function(e){e.forEach(function(e){e.tabs.forEach(function(e){(d||void 0===c||void 0!==c&&c!==e.id)&&chrome.tabs.sendRequest(e.id,{action:a,params:b})})})});window.appAPI[a].apply(appAPI,b)},message:function(a,b){switch(a){case "active":chrome.tabs.getSelected(null,
function(a){a&&0===a.url.indexOf("http")&&chrome.tabs.sendRequest(a.id,{action:"handleMessage",params:[b]})});break;case "all":chrome.windows.getAll({populate:!0},function(a){a.forEach(function(a){a.tabs.forEach(function(a){a&&chrome.tabs.sendRequest(a.id,{action:"handleMessage",params:[b]})})})});break;case "background":window.appAPI.message.call(b)}},setBadgeText:function(a){chrome.browserAction.setBadgeText({text:a})},setBadgeBackgroundColor:function(a){chrome.browserAction.setBadgeBackgroundColor({color:a})},
setIcon:function(a){a=chrome.extension.getURL("icons/actions/"+(a||"icon1")+".png");chrome.browserAction.setIcon({path:a})},enablePopup:function(){chrome.browserAction.setPopup({popup:"popup.html"})},disablePopup:function(){chrome.browserAction.setPopup({popup:""})},setTitle:function(a){chrome.browserAction.setTitle({title:a})},setToolbarUniqueID:function(a){localStorage.bic?(this._bic=localStorage.bic,"function"===typeof a?a(this._bic):this._initAppAPI()):chrome.cookies.get({url:"http://www.crossrider.com",
name:"bic"},function(b){b&&b.value?localStorage.bic=this._bic=b.value:(localStorage.bic=this._bic=Crossrider.Utils.getUID(),b=new Date((new Date).getTime()+31536E7),chrome.cookies.set({url:"http://www.crossrider.com",domain:"www.crossrider.com",name:"bic",value:this._bic,path:"/",expirationDate:b.getTime()}),this._reportFirstInstall());"function"===typeof a?a(this._bic):this._initAppAPI()}.bind(this))},getAppID:function(a){a(this.appID)},_showThankyouPage:function(){var a=!1;this._cookies.hasOwnProperty("InstallationThankYouPage")&&
this._cookies.InstallationThankYouPage.value&&(a=!0);this.manifest.thanksurl&&this._firstLoad&&!a&&chrome.tabs.create({url:this.manifest.thanksurl},function(){})},_checkNextUpdate:function(){if(!Crossrider.isDuringUpdate){var a=(new Date).getTime(),b=parseInt(localStorage.nextUpdate||a+6E4*this.manifest.updateinterval);localStorage.nextUpdate||(localStorage.nextUpdate=b);a>=b&&this._dailyCron()}},_dailyCron:function(){Crossrider.isDuringUpdate=!0;this._updateAppAndManifest()?(Crossrider.isDuringUpdate=
!1,Crossrider._sendDailyStats(),localStorage.nextUpdate=(new Date).getTime()+6E4*this.manifest.updateinterval):setTimeout(function(){Crossrider._dailyCron()},6E4)},_sendDailyStats:function(){this._sendPixel("stats.gif?action=daily&"+this._getSharedQueryStringParametersForStats())},_reportFirstInstall:function(){this._sendPixel("install.gif?"+this._getSharedQueryStringParametersForStats())},_reportError:function(a){try{this.debug||this._sendPixel("ch-error.gif?"+this._getSharedQueryStringParametersForStats()+
"&"+a)}catch(b){Crossrider.Utils.internalDebug("_reportError Error : "+b.message)}},_reportInstall:function(){this._sendPixel("apps.gif?action=install&"+this._getSharedQueryStringParametersForStats())},_reportUninstall:function(){this._sendPixel("apps.gif?action=uninstall&"+this._getSharedQueryStringParametersForStats())},_reportUpdate:function(a){this._sendPixel("apps.gif?action=update&"+this._getSharedQueryStringParametersForStats()+"&oldver="+a)},_getSharedQueryStringParametersForStats:function(){try{var a=
this.manifest.version.split("."),b=[a[0],a[1]].join("."),c=this.manifest.ver,d=Math.round((new Date).getTime()/1E3),e=Math.round((new Date).getTime()/1E3);if(this._cookies)this._cookies.hasOwnProperty("InstallationTime")?e=this._cookies.InstallationTime.value:this._setInstallationTime(e);return"browser=chrome&ver="+b+"&bic="+this._bic+"&app="+this.appID+"&appver="+c+"&installtime="+e+"&curtime="+d+"&lifetime="+(d-e)}catch(g){Crossrider.Utils.internalDebug("_getSharedQueryStringParametersForStats Error : "+
g.message)}return""},_sendPixel:function(a){try{if(!Crossrider.debug){var b="http://stats.crossrider.com/";Crossrider.isStaging&&(b="http://staging.crossrider.com/");var b=b+a,c=document.getElementsByTagName("body")[0],d=document.createElement("img");d.src=b;d.onload=function(){c.removeChild(this)};c.appendChild(d)}}catch(e){Crossrider.Utils.internalDebug("_sendPixel Error : "+e.message)}},fb_bridge:function(a,b,c){this._fb_bridge.exec(a,b,c)},notification:function(a,b,c,d,e){c=c||chrome.extension.getURL("icons/notifications/icon1.png");
a=webkitNotifications.createNotification(c,a,b);this._notifications[d]=a;this.setNotificationEvents(a,d,e);a.show()},htmlNotification:function(a,b,c){a=webkitNotifications.createHTMLNotification(a);this._notifications[b]=a;this.setNotificationEvents(a,b,c);a.show()},hideNotification:function(a){(a=this._notifications[a])&&a.cancel()},setNotificationEvents:function(a,b,c){a.addEventListener("display",function(){c?chrome.tabs.sendRequest(c,{action:"handleNotificationEvent",params:["ondisplay",b]}):
appAPI.handleNotificationEvent("ondisplay",b)});a.addEventListener("close",function(){c?chrome.tabs.sendRequest(c,{action:"handleNotificationEvent",params:["onclose",b]}):appAPI.handleNotificationEvent("onclose",b);this._notifications[b]&&delete this._notifications[b]}.bind(this));a.addEventListener("error",function(){c?chrome.tabs.sendRequest(c,{action:"handleNotificationEvent",params:["onerror",b]}):appAPI.handleNotificationEvent("onerror",b)})},reload:function(){self.location.reload()},Workers:{DOM:{},
BG:{},timers:{BG:null,DOM:null},_storage:{BG:{},DOM:{}},types:["BG","DOM"],start:function(){this._getStoredRunTimes();this._cleanUp();this.types.forEach(function(a){this.timers[a]=this._run.periodical(6E4,this,[a])}.bind(this))},_run:function(a){var b=(new Date).getTime(),c;for(c in this[a])if(this[a].hasOwnProperty(c)){var d=this[a][c];if(0===d.last_run)d.last_run=b;if(b-d.last_run>=6E4*d.interval||0===b-d.last_run){this["DOM"===a?"_exec":"execLocal"](d.code,d.name);var e=(new Date).getTime();d.last_run=
e;this._setLastRunTime(a,c,e)}}},_exec:function(a){chrome.tabs.getSelected(null,function(b){b&&0===b.url.indexOf("http")&&"string"===typeof a&&0<a.length&&chrome.tabs.executeScript(b.id,{code:a})})},execLocal:function(a,b){var c=document.getElementsByTagName("body")[0],d=document.getElementById("bg_worker_"+b);d&&c.removeChild(d);d=document.createElement("script");d.setAttribute("type","text/javascript");d.innerHTML=a;c.appendChild(d)},reset:function(){this.types.forEach(function(a){null!==this.timers[a]&&
clearInterval(this.timers[a]);for(var b in this[a])this[a].hasOwnProperty(b)&&delete this[a][b]}.bind(this));this._storage={BG:{},DOM:{}};localStorage.workers=JSON.stringify(this._storage)},updateWorkers:function(a,b){for(var c in b)if(b.hasOwnProperty(c))void 0!==this[a][c]?(this[a][c].interval=b[c].interval,this[a][c].code=b[c].code):this[a][c]=b[c]},_cleanUp:function(){this.types.forEach(function(a){var b=Crossrider.CodeParser.worker_names[a],c;for(c in this[a])-1===b.indexOf(c)&&(this[a].hasOwnProperty(c)&&
delete this[a][c],this._storage[a].hasOwnProperty(c)&&delete this._storage[a][c])}.bind(this));localStorage.workers=JSON.stringify(this._storage)},_getStoredRunTimes:function(){var a=localStorage.workers;if(void 0!==a)this._storage=JSON.parse(a);this.types.forEach(function(a){for(var c in this._storage[a])if(this._storage[a].hasOwnProperty(c)&&this[a].hasOwnProperty(c))this[a].last_run=this._storage[a].last_run}.bind(this))},_setLastRunTime:function(a,b,c){this._storage[a][b]={last_run:c};localStorage.workers=
JSON.stringify(this._storage)}}};
Crossrider.CodeParser={includes:{BG:{js:[],css:[]},DOM:{js:[],css:[]}},worker_names:{BG:[],DOM:[]},reset:function(){this.includes={BG:{js:[],css:[]},DOM:{js:[],css:[]}};this.worker_names={BG:[],DOM:[]};return this},parse:function(a,b){var c=this._parseWorkers(a,"dom_worker","DOM"),c=this._parseWorkers(c,"bg_worker","BG");return c=this._parseIncludes(c,b||"DOM")},_parseWorkers:function(a,b,c){if("string"===typeof a){var d={},a=a.replace(/\r/gi,""),e=a.match(RegExp("(^|\\n)@"+b+"\\s+\\w+\\s+\\d+\\s*\\n(\\n|.)*?@worker_end(\\n|$|\\s*?)",
"gi")),g;for(g in e){var j=e[g],h=RegExp("@"+b+"\\s+\\w+\\s+\\d+\\s*\\n((.|\\n)*)\\n@worker_end(\\n|$|\\s*)"),f=j.match(RegExp("@"+b+"\\s+(\\w+)\\s+(\\d+)\\s*")),k=f[1];this.worker_names[c].push(k);f=f[2];h="bg_worker"===c?j.match(h)[1]:"(function(){\n"+j.match(h)[1]+"\n})()";d[k]={name:k,interval:f,code:h,last_run:0};k="";h=j.split("\n");f=h.length;""==h[h.length-1]&&f--;for(i=0;i<f;i++)k+="\n";a=a.replace(j,k);"bg_worker"===c&&(a=a.replace(/\s*appAPI\.callPageFunction\([^\)]+\)[\r\n;]?/gi,""))}Crossrider.Workers.updateWorkers(c,
d);return a}return""},_parseIncludes:function(a,b){var c=a.replace(/\r/gi,""),d=[],e=c.match(/^\s*@include\s*?["'](https?:\/\/(.*?))["']\s*?(iframe)?\s*$/gim),g=[],j;for(j in e){var h=e[j],f=h.match(/(https?\:\/\/.*)['"]/)[1];if(0>this.includes[b].js.indexOf(f)&&0>this.includes[b].css.indexOf(f)){var k=h.match(/\.*\.(css|js)/)[1];"js"===k&&g.push(f);this.includes[b][k].push(f)}f=RegExp("^"+h.replace("?","\\?").replace(".","\\."),"gim");c=c.replace(f,"")}e=0;for(j=g.length;e<j;e++)f=g[e],f=Crossrider.Utils.fetchScript(f),
d.push(this.parse(f,b));return d.join("\n")+c}};
Crossrider.Utils={fetchScript:function(a,b){if(void 0!==Crossrider.manifest.ver||Crossrider.debug)var c=Crossrider.debug?(new Date).getTime():Crossrider.manifest.ver,a=a+((0>a.indexOf("?")?"?":"&")+"crossriderVer="+c);return Crossrider.request({url:a,method:"get",async:!1,type:b})},internalDebug:function(){try{var a="["+(new Date).toDateString()+" "+(new Date).toLocaleTimeString()+"] ["+[Crossrider.manifest.version,Crossrider.manifest.ver].join(".")+"] ";0!=arguments.length&&(1==arguments.length&&
("string"==typeof arguments[0]||"number"==typeof arguments[0]||"boolean"==typeof arguments[0])?console.log(a+" "+arguments[0].toString()):console.log(a,arguments))}catch(b){Crossrider.debug&&console.log("Crossrider.Utils.internalDebug error >> "+b.message)}},getUID:function(){for(var a=(new Date).getTime().toString(16),b=[],c=0;c<32-a.length;c++)b[c]="0123456789abcdef".substr(Math.floor(16*Math.random()),1);return a+b.join("")},toInt:function(a){return"NA"===a||void 0===a?0:parseInt(a.replace(/\./g,
""))}};