var AppApi=function(){};
AppApi.prototype={_dom:{},_faye:{callbacks:{},asyncCallbacks:{}},_removedCookies:{},request:Request,time:Time,dom:DOM,db:DB,init:function(){this.cookie=new Cookie(this);this.push=new Push(this);this.chrome=new ChromeAPI(this);this.browserAction=this.chrome.browserAction;this.analytics=new Analytics(this);this.message=new Message;this.installer=new Installer(this);this._initInternalMessaging();this._getUserScripts()},_initInternalMessaging:function(){chrome.extension.onRequest.addListener(this._onRequest.bind(this))},_getUserScripts:function(){chrome.extension.sendRequest({action:"getAppID",
passCallback:!0},function(a){if(null===document.getElementById("crossrider-app-stub"+a)){var b=document.createElement("div");b.id="crossrider-app-stub"+a;document.getElementsByTagName("body")[0].appendChild(b);chrome.extension.sendRequest({action:"addUserScripts"},function(){})}})},_onRequest:function(a,b,c){if((b=a.action)&&"function"===typeof this[b]){var d=a.params&&"function"===typeof a.params.push?a.params:[];!0===a.passCallback&&d.push(c);this[b].apply(this,d)}!a.passCallback&&c&&"function"===
typeof c&&c()},initContentScript:function(a,b,c,d,f,e){a.forEach(function(a){this.dom.addRemoteCSS(a)}.bind(this));this.tabID=c;this.manifest=f;this.appID=f.crossrider.appID;this.cr_version=f.version;this.version=f.ver;this.platform=f.platform;this.debugMode=f.crossrider.debug;this._cookies=JSON.parse(b);this.db.init(this);this.debug=new Debugger(this);this.message.setTabId(c);this.fbAPI=new FacebookAPI(this);this.asyncAPI=AsyncAPI.init(this);d?(this._bic=d,this.appInfo=new AppInfo(this),e()):chrome.extension.sendRequest({action:"setToolbarUniqueID",
params:[],passCallback:!0},function(a){this._bic=a;this.appInfo=new AppInfo(this);e()}.bind(this))},openURL:function(a,b){chrome.extension.sendRequest({action:"openURL",params:[a,b]},function(){})},superAlert:function(a){chrome.extension.sendRequest({action:"superAlert",params:[a]},function(){})},updateCookie:function(a,b){var c=this;this._cookies?this._removedCookies[a]?delete this._removedCookies[a]:this._cookies[a]={value:b.value,expires:b.expires}:setTimeout(function(){c.updateCookie(a,b)},25)},
unsetCookie:function(a){this._cookies[a]&&(this._removedCookies[a]=!0,delete this._cookies[a])},updateRealCookie:function(a,b){this._removedCookies["real"+a]?delete this._removedCookies["real"+a]:this._cookies.mysite[a]={value:b.value,expires:b.expires}},unsetRealCookie:function(a){this._cookies.mysite[a]&&(this._removedCookies["real"+a]=!0,delete this._cookies.mysite[a])},respond:function(a,b,c){c=c?"asyncCallbacks":"callbacks";if(this._faye[c][a])this._faye[c][a](b)},isDebugMode:function(){return this.debugMode},
getCrossriderID:function(){return this._bic},fb_respond:function(a,b){this.fbAPI.callback(a,b)},handleMessage:function(a){this.message.call(a)},background:{reload:function(){chrome.extension.sendRequest({action:"reload"},function(){})}},getAPIInfo:function(){return{appID:this.appID,cr_version:this.cr_version,version:this.version,platform:this.platform}},selectedText:function(a,b){function c(){if(window.getSelection)return window.getSelection();if(document.getSelection)return document.getSelection();
var a=document.selection&&document.selection.createRange();return a.text?a.text:!1}if(null==a)this.debug("selectedText: no callback function provided.");else{null==b&&(b={});b.lastSelection="";b.minlength=b.minlength||1;b.maxlength=b.maxlength||99999999;var d;switch(typeof b.element){case "undefined":d=$jquery("body");break;case "object":if(b.element instanceof jQuery)d=b.element;else{this.debug("selectedText: element provided as an unrecorgnize object.");return}break;case "string":d=$jquery(b.element);
break;default:this.debug("selectedText: unknown element.");return}d.mouseup(function(d){var e=c();e&&""+e==b.lastSelection?b.lastSelection="":(b.lastSelection=""+e,e&&(""+e).length>=b.minlength&&(""+e).length<=b.maxlength&&a(e,d))})}},shortcut:{all_shortcuts:{},add:function(a,b,c){var d={type:"keydown",propagate:!1,disable_in_input:!1,target:document,keycode:!1};if(c)for(var f in d)"undefined"===typeof c[f]&&(c[f]=d[f]);else c=d;d=c.target;"string"===typeof c.target&&(d=document.getElementById(c.target));
a=a.toLowerCase();f=function(e){e=e||window.event;if(c.disable_in_input){var d;if(e.target)d=e.target;else if(e.srcElement)d=e.srcElement;if(3===d.nodeType)d=d.parentNode;if("INPUT"==d.tagName||"TEXTAREA"==d.tagName)return}if(e.keyCode)code=e.keyCode;else if(e.which)code=e.which;d=String.fromCharCode(code).toLowerCase();188==code&&(d=",");190==code&&(d=".");var f=a.split("+"),g=0,i={"`":"~",1:"!",2:"@",3:"#",4:"$",5:"%",6:"^",7:"&",8:"*",9:"(","0":")","-":"_","=":"+",";":":","'":'"',",":"<",".":">",
"/":"?","\\":"|"},s={esc:27,escape:27,tab:9,space:32,"return":13,enter:13,backspace:8,scrolllock:145,scroll_lock:145,scroll:145,capslock:20,caps_lock:20,caps:20,numlock:144,num_lock:144,num:144,pause:19,"break":19,insert:45,home:36,"delete":46,end:35,pageup:33,page_up:33,pu:33,pagedown:34,page_down:34,pd:34,left:37,up:38,right:39,down:40,f1:112,f2:113,f3:114,f4:115,f5:116,f6:117,f7:118,f8:119,f9:120,f10:121,f11:122,f12:123},j=!1,l=!1,m=!1,n=!1,o=!1,p=!1,q=!1,r=!1;e.ctrlKey&&(n=!0);e.shiftKey&&(l=
!0);e.altKey&&(p=!0);e.metaKey&&(r=!0);for(var h=0;k=f[h],h<f.length;h++)"ctrl"==k||"control"==k?(g++,m=!0):"shift"==k?(g++,j=!0):"alt"==k?(g++,o=!0):"meta"==k?(g++,q=!0):1<k.length?s[k]==code&&g++:c.keycode?c.keycode==code&&g++:d==k?g++:i[d]&&e.shiftKey&&(d=i[d],d==k&&g++);if(g==f.length&&n==m&&l==j&&p==o&&r==q&&(b(e),!c.propagate))return e.cancelBubble=!0,e.returnValue=!1,e.stopPropagation&&(e.stopPropagation(),e.preventDefault()),!1};this.all_shortcuts[a]={callback:f,target:d,event:c.type};d.addEventListener?
d.addEventListener(c.type,f,!1):d.attachEvent?d.attachEvent("on"+c.type,f):d["on"+c.type]=f},remove:function(a){var a=a.toLowerCase(),b=this.all_shortcuts[a];delete this.all_shortcuts[a];if(b){var a=b.event,c=b.target,b=b.callback;c.detachEvent?c.detachEvent("on"+a,b):c.removeEventListener?c.removeEventListener(a,b,!1):c["on"+a]=!1}}},matchPages:function(){for(var a=!1,b=0;b<arguments.length;b++){var c=arguments[b],d=!1;"string"==typeof c?(c=c.replace(/\./,"\\.").replace(/\*/,".*"),d=document.location.href.match(RegExp("^http.?\\:\\/\\/"+
c))?!0:!1):"object"==typeof c&&(d=document.location.href.match(c)?!0:!1);if(a=a||d)break}return a}};var appAPI=new AppApi;appAPI.init();$jquery=$$jquery.noConflict();